// Generated by CoffeeScript 1.7.1
var componentStatic, glob, mergeJsons, path,
  __hasProp = {}.hasOwnProperty;

glob = require('glob');

path = require('path');

mergeJsons = function(files) {
  var dir, file, json, prefix, result, staticDir, _i, _len, _ref;
  result = {};
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    json = require('./' + file);
    if (!json["static"]) {
      continue;
    }
    _ref = json["static"];
    for (prefix in _ref) {
      if (!__hasProp.call(_ref, prefix)) continue;
      staticDir = _ref[prefix];
      dir = path.dirname(file);
      result[prefix] = path.normalize(path.join(dir, staticDir));
    }
  }
  return result;
};

componentStatic = function(callback) {
  return glob('**/component.json', function(err, files) {
    return callback(mergeJsons(files));
  });
};

componentStatic.sync = function() {
  var files;
  files = glob.sync('**/component.json');
  return mergeJsons(files);
};

module.exports = componentStatic;
